swagger: '2.0'
info:
  title: Bank Argent API documentation Mk2 (consulting)
  description: Contains all available API endpoints in this codebase
  version: '1.1.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /accounts/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User accounts API
      description: API for fetching transactions
      #produces:
       # - application/json
      responses:
        '200':
          description: Accounts and transactions retrieved
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Bad request. Synthax problem in the request.
        '401':
          description: Unauthorized. Authorization information is missing or invalid.
        '404':
          description: Not found.
        '500':
          description: Unexpected internal server error.
  /accounts/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Get a specific account
      description: API for fetching a specific account
      parameters:
        - name: accountId
          in: path
          required: true
          description: ID of the account to retrieve
          type: string
      responses:
        '200':
          description: Account retrieved successfully
          schema:
            $ref: '#/definitions/Account'
        '400':
          description: Bad request. Synthax problem in the request.
        '401':
          description: Unauthorized. Authorization information is missing or invalid.
        '404':
          description: Not found.
        '500':
          description: Unexpected internal server error.
  /accounts/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: New transactions
      description: API for creating transactions
      parameters:
        - in: body
          name: body
          description: Update transaction note
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Bad request. Synthax problem in the request.
        '401':
          description: Unauthorized. Authorization information is missing or invalid.
        '404':
          description: Not found.
        '500':
          description: Unexpected internal server error.
  /accounts/transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: User accounts API
      description: API for reading a specific transaction
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: Unique ID of the transaction to be updated
      #produces:
       # - application/json
      responses:
        '200':
          description: Transaction retrieved successfully.
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Bad request. Synthax problem in the request.
        '401':
          description: Unauthorized. Authorization information is missing or invalid.
        '404':
          description: Not found.
        '500':
          description: Unexpected internal server error.
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update
      description: API for updating a transaction
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: Unique ID of the transaction to be updated
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              type:
                type: string
                description: Type of the transaction
              category:
                type: string
                description: Category of the transaction
            required:
              - type
              - category
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Bad request. Synthax problem in the request.
        '401':
          description: Unauthorized. Authorization information is missing or invalid.
        '404':
          description: Not found.
        '500':
          description: Unexpected internal server error.
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    properties:
      id:
        type: string
        description: unique id of the transaction 
      accountId:
        type: string
        description: unique id of the account where the transaction occures
      date:
        type: string
        description: date of transaction
      title:
        type: string
        description: description of the transaction
      amount:
        type: number
        description: amount of the transaction
      type:
        type: string
        description: type of transaction
      category:
        type: string
        description: category of transaction
      note:
        type: string
        description: note about the transaction (facultative)
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Account:
    properties:
      accountId:
        type: string
        description: unic Id of the account
      accountName:
        type: string
        description: name of the account
      accountBalance:
        type: number
        description: available balance of the account
